name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache SonarCloud files
        uses: actions/cache@v4  # ✅ Updated to v4
        with:
          path: ~/.sonar/cache
          key: sonar-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            sonar-cache-${{ runner.os }}-

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag kokatim/final-python:${{ github.run_number }}-${{ github.sha }}

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.USERNAME }}
          DOCKER_PASS: ${{ secrets.PASSWORD }}
        run: echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin

      - name: Push Docker image
        run: docker push kokatim/final-python:${{ github.run_number }}-${{ github.sha }}

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2  # ✅ Updated action
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # ✅ Uses secure token
