name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

      steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lidorlg/my-image-name:${{ github.run_number }}-${GITHUB_SHA}
    - name: docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: docker push
      run: docker push lidorlg/my-image-name:${{ github.run_number }}-${GITHUB_SHA}
